---
# Common AVD group variables
fabric_name: FABRIC

underlay_routing_protocol: ebgp
overlay_routing_protocol: ebgp

# Local users
local_users:
  - name: tony
    privilege: 15
    role: network-admin
    sha512_password: $6$2HC2gweRsQ.pgMMJ$G7sQKhDUV8Kxw9d0bN9PCpqKPoB7w9EEieDb3IA3vgK3Gf13EuBLJZ.TTHjZLbMnLO3X0Hsdu.iDpHVozaX7O.
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaaW0yCS+kwtUVIJdwCVaw2+Ul/yYhaPXYltoVcszcEJPWCSwAmMdvrlecxcyEfrs1KJLYVLD8RwmMRlMRrteYJzmk8MGuAyNxQMcma0EWI78suzJOlxGczxwUzZY2+vYwLgWQZPYEZeScjY8ko68r+sEUmgg+y/WC+OGshtytqahs1zaJhDHwu2y3GAW9KnCA1vQL8qyaXvTKkci6+unMlwdc7jTL7bktoudWFKAAHxVtJf0SdBGvWdbbh3JgAt3mHtjKMfm+8qQgv1mfr6Sn41tLlsmn/RTsMMkDbuYVmpjXFSb6LXwf/ylx1zc/FxJHHXh4yD0wOKD3rYEIjndF7uGEqrs1BZtje50L6YPVcjUCGI9kL4R1BUI8uzTmTLATOmDJ03KAaTnXwkhlW96FQshJjiDL4K9FZUaYww6vEp2nk2XOaXxyB1JXe0/2A/H57f2wIR1TwdqAbcHOkGLqj0mS+focnRJvaxPk6ytIGmfRqF9n8K0RLMXN9s/G+sk=
  - name: admin
    privilege: 15
    role: network-admin
    sha512_password: $6$E3EsaKSY8pKgghHP$DMbYzJMIvUpcHnJv1j8nE47wYv4VbECq1oacBXukkYd/IH4D0c9n7VmijLyob4GEZfWBlZYPUi8es9EaGl387/
    ssh_key: ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDaaW0yCS+kwtUVIJdwCVaw2+Ul/yYhaPXYltoVcszcEJPWCSwAmMdvrlecxcyEfrs1KJLYVLD8RwmMRlMRrteYJzmk8MGuAyNxQMcma0EWI78suzJOlxGczxwUzZY2+vYwLgWQZPYEZeScjY8ko68r+sEUmgg+y/WC+OGshtytqahs1zaJhDHwu2y3GAW9KnCA1vQL8qyaXvTKkci6+unMlwdc7jTL7bktoudWFKAAHxVtJf0SdBGvWdbbh3JgAt3mHtjKMfm+8qQgv1mfr6Sn41tLlsmn/RTsMMkDbuYVmpjXFSb6LXwf/ylx1zc/FxJHHXh4yD0wOKD3rYEIjndF7uGEqrs1BZtje50L6YPVcjUCGI9kL4R1BUI8uzTmTLATOmDJ03KAaTnXwkhlW96FQshJjiDL4K9FZUaYww6vEp2nk2XOaXxyB1JXe0/2A/H57f2wIR1TwdqAbcHOkGLqj0mS+focnRJvaxPk6ytIGmfRqF9n8K0RLMXN9s/G+sk=


p2p_uplinks_mtu: 1550



spine:
  defaults:
    platform: cEOS-lab
    loopback_ipv4_pool: 10.255.4.0/24
    bgp_as: 65001
  nodes:
    - name: spine1
      id: 1
      mgmt_ip: 172.20.20.101/24
    - name: spine2
      id: 2
      mgmt_ip: 172.20.20.102/24
    - name: spine3
      id: 3
      mgmt_ip: 172.20.20.103/24


l3leaf:
  defaults:
    bgp_as: 65101-65190
    platform: cEOS-lab
    loopback_ipv4_pool: 10.255.4.0/24
    vtep_loopback_ipv4_pool: 10.255.5.0/24
    uplink_switches: ['spine1', 'spine2', 'spine3']
    uplink_interfaces: ['Ethernet3', 'Ethernet4', 'Ethernet5']
    uplink_ipv4_pool: 10.255.0.0/22
    mlag_peer_ipv4_pool: 10.255.6.0/24
    mlag_peer_l3_ipv4_pool: 10.255.7.0/24
    mlag_interfaces: [Ethernet1, Ethernet2]
    virtual_router_mac_address: 02:1c:73:00:00:99
    spanning_tree_priority: 4096
    spanning_tree_mode: mstp
    mlag: true 

  node_groups:
    - group: RACK1
      nodes:
        - name: leaf1
          id: 11
          mgmt_ip: 172.20.20.11/24
          uplink_switch_interfaces: [Ethernet2, Ethernet2, Ethernet2]
        - name: leaf2
          id: 12
          mgmt_ip: 172.20.20.12/24
          uplink_switch_interfaces: [Ethernet3, Ethernet3, Ethernet3]
    - group: RACK2
      nodes:
        - name: leaf3
          id: 13
          mgmt_ip: 172.20.20.13/24
          uplink_switch_interfaces: [Ethernet4, Ethernet4, Ethernet4]
        - name: leaf4
          id: 14
          mgmt_ip: 172.20.20.14/24
          uplink_switch_interfaces: [Ethernet5, Ethernet5, Ethernet5]
    - group: RACK3
      nodes:
        - name: leaf5
          id: 15
          mgmt_ip: 172.20.20.15/24
          uplink_switch_interfaces: [Ethernet6, Ethernet6, Ethernet6]
        - name: leaf6
          id: 16
          mgmt_ip: 172.20.20.16/24
          uplink_switch_interfaces: [Ethernet7, Ethernet7, Ethernet7]
    - group: RACK4
      nodes:
        - name: leaf7
          id: 17
          mgmt_ip: 172.20.20.17/24
          uplink_switch_interfaces: [Ethernet8, Ethernet8, Ethernet8]
        - name: leaf8
          id: 18
          mgmt_ip: 172.20.20.18/24
          uplink_switch_interfaces: [Ethernet9, Ethernet9, Ethernet9]
    - group: RACK5
      nodes:
        - name: leaf9
          id: 19
          mgmt_ip: 172.20.20.19/24
          uplink_switch_interfaces: [Ethernet10, Ethernet10, Ethernet10]
        - name: leaf10
          id: 20
          mgmt_ip: 172.20.20.20/24
          uplink_switch_interfaces: [Ethernet11, Ethernet11, Ethernet11]
    - group: RACK6
      nodes:
        - name: leaf11
          id: 21
          mgmt_ip: 172.20.20.21/24
          uplink_switch_interfaces: [Ethernet12, Ethernet12, Ethernet12]
        - name: leaf12
          id: 22
          mgmt_ip: 172.20.20.22/24
          uplink_switch_interfaces: [Ethernet13, Ethernet13, Ethernet13]
    - group: RACK7
      nodes:
        - name: leaf13
          id: 23
          mgmt_ip: 172.20.20.23/24
          uplink_switch_interfaces: [Ethernet14, Ethernet14, Ethernet14]
        - name: leaf14
          id: 24
          mgmt_ip: 172.20.20.24/24
          uplink_switch_interfaces: [Ethernet15, Ethernet15, Ethernet15]
    - group: RACK8
      nodes:
        - name: leaf15
          id: 25
          mgmt_ip: 172.20.20.25/24
          uplink_switch_interfaces: [Ethernet16, Ethernet16, Ethernet16]
        - name: leaf16
          id: 26
          mgmt_ip: 172.20.20.26/24
          uplink_switch_interfaces: [Ethernet17, Ethernet17, Ethernet17]
    - group: RACK9
      nodes:
        - name: leaf17
          id: 27
          mgmt_ip: 172.20.20.27/24
          uplink_switch_interfaces: [Ethernet18, Ethernet18, Ethernet18]
        - name: leaf18
          id: 28
          mgmt_ip: 172.20.20.28/24
          uplink_switch_interfaces: [Ethernet19, Ethernet19, Ethernet19]
    - group: RACK10
      nodes:
        - name: leaf19
          id: 29
          mgmt_ip: 172.20.20.29/24
          uplink_switch_interfaces: [Ethernet20, Ethernet20, Ethernet20]
        - name: leaf20
          id: 30
          mgmt_ip: 172.20.20.30/24
          uplink_switch_interfaces: [Ethernet21, Ethernet21, Ethernet21]
    - group: RACK11
      nodes:
        - name: leaf21
          id: 31
          mgmt_ip: 172.20.20.31/24
          uplink_switch_interfaces: [Ethernet22, Ethernet22, Ethernet22]
        - name: leaf22
          id: 32
          mgmt_ip: 172.20.20.32/24
          uplink_switch_interfaces: [Ethernet23, Ethernet23, Ethernet23]
    - group: RACK12
      nodes:
        - name: leaf23
          id: 33
          mgmt_ip: 172.20.20.33/24
          uplink_switch_interfaces: [Ethernet24, Ethernet24, Ethernet24]
        - name: leaf24
          id: 34
          mgmt_ip: 172.20.20.34/24
          uplink_switch_interfaces: [Ethernet25, Ethernet25, Ethernet25]
    - group: RACK13
      nodes:
        - name: leaf25
          id: 35
          mgmt_ip: 172.20.20.35/24
          uplink_switch_interfaces: [Ethernet26, Ethernet26, Ethernet26]
        - name: leaf26
          id: 36
          mgmt_ip: 172.20.20.36/24
          uplink_switch_interfaces: [Ethernet27, Ethernet27, Ethernet27]
    - group: RACK14
      nodes:
        - name: leaf27
          id: 37
          mgmt_ip: 172.20.20.37/24
          uplink_switch_interfaces: [Ethernet28, Ethernet28, Ethernet28]
        - name: leaf28
          id: 38
          mgmt_ip: 172.20.20.38/24
          uplink_switch_interfaces: [Ethernet29, Ethernet29, Ethernet29]
    - group: RACK15
      nodes:
        - name: leaf29
          id: 39
          mgmt_ip: 172.20.20.39/24
          uplink_switch_interfaces: [Ethernet30, Ethernet30, Ethernet30]
        - name: leaf30
          id: 40
          mgmt_ip: 172.20.20.40/24
          uplink_switch_interfaces: [Ethernet31, Ethernet31, Ethernet31]
    - group: RACK16
      nodes:
        - name: leaf31
          id: 41
          mgmt_ip: 172.20.20.41/24
          uplink_switch_interfaces: [Ethernet32, Ethernet32, Ethernet32]
        - name: leaf32
          id: 42
          mgmt_ip: 172.20.20.42/24
          uplink_switch_interfaces: [Ethernet33, Ethernet33, Ethernet33]
    - group: RACK17
      nodes:
        - name: leaf33
          id: 43
          mgmt_ip: 172.20.20.43/24
          uplink_switch_interfaces: [Ethernet34, Ethernet34, Ethernet34]
        - name: leaf34
          id: 44
          mgmt_ip: 172.20.20.44/24
          uplink_switch_interfaces: [Ethernet35, Ethernet35, Ethernet35]
    - group: RACK18
      nodes:
        - name: leaf35
          id: 45
          mgmt_ip: 172.20.20.45/24
          uplink_switch_interfaces: [Ethernet36, Ethernet36, Ethernet36]
        - name: leaf36
          id: 46
          mgmt_ip: 172.20.20.46/24
          uplink_switch_interfaces: [Ethernet37, Ethernet37, Ethernet37]
    - group: RACK19
      nodes:
        - name: leaf37
          id: 47
          mgmt_ip: 172.20.20.47/24
          uplink_switch_interfaces: [Ethernet38, Ethernet38, Ethernet38]
        - name: leaf38
          id: 48
          mgmt_ip: 172.20.20.48/24
          uplink_switch_interfaces: [Ethernet39, Ethernet39, Ethernet39]
    - group: RACK20
      nodes:
        - name: leaf39
          id: 49
          mgmt_ip: 172.20.20.49/24
          uplink_switch_interfaces: [Ethernet40, Ethernet40, Ethernet40]
        - name: leaf40
          id: 50
          mgmt_ip: 172.20.20.50/24
          uplink_switch_interfaces: [Ethernet41, Ethernet41, Ethernet41]
    - group: RACK21
      nodes:
        - name: leaf41
          id: 51
          mgmt_ip: 172.20.20.51/24
          uplink_switch_interfaces: [Ethernet42, Ethernet42, Ethernet42]
        - name: leaf42
          id: 52
          mgmt_ip: 172.20.20.52/24
          uplink_switch_interfaces: [Ethernet43, Ethernet43, Ethernet43]
    - group: RACK22
      nodes:
        - name: leaf43
          id: 53
          mgmt_ip: 172.20.20.53/24
          uplink_switch_interfaces: [Ethernet44, Ethernet44, Ethernet44]
        - name: leaf44
          id: 54
          mgmt_ip: 172.20.20.54/24
          uplink_switch_interfaces: [Ethernet45, Ethernet45, Ethernet45]
    - group: RACK23
      nodes:
        - name: leaf45
          id: 55
          mgmt_ip: 172.20.20.55/24
          uplink_switch_interfaces: [Ethernet46, Ethernet46, Ethernet46]
        - name: leaf46
          id: 56
          mgmt_ip: 172.20.20.56/24
          uplink_switch_interfaces: [Ethernet47, Ethernet47, Ethernet47]
    - group: RACK24
      nodes:
        - name: leaf47
          id: 57
          mgmt_ip: 172.20.20.57/24
          uplink_switch_interfaces: [Ethernet48, Ethernet48, Ethernet48]
        - name: leaf48
          id: 58
          mgmt_ip: 172.20.20.58/24
          uplink_switch_interfaces: [Ethernet49, Ethernet49, Ethernet49]
    - group: BORDERLEAFS
      nodes:
        - name: borderleaf1
          id: 61
          uplink_switch_interfaces: [Ethernet52, Ethernet52, Ethernet52]
          mgmt_ip: 172.20.20.91/24
        - name: borderleaf2
          id: 62
          uplink_switch_interfaces: [Ethernet53, Ethernet53, Ethernet53]
          mgmt_ip: 172.20.20.92/24

# Needed for vEOS/cEOS
bgp_update_wait_install: false
bgp_update_wait_for_convergence: false

mgmt_interface: Management0
mgmt_interface_vrf: MGMT
mgmt_gateway: 172.20.20.1
name_servers: [192.168.1.9]


### Housekeeping



# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
# ntp_settings:
#   server_vrf: MGMT
#   servers:
#     - name: 192.168.1.9



management_api:
  enable_https: true

aaa_authentication:
  login:
    default: local

aaa_authorization:
  exec: 
    default: local

          #     - aaa authentication login default local 
          # - aaa authorization exec default local


